version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - FREEPIK_API_KEY=${FREEPIK_API_KEY}
      - FREEPIK_WEBHOOK_SECRET=${FREEPIK_WEBHOOK_SECRET}
      - FREEPIK_WEBHOOK_URL=${FREEPIK_WEBHOOK_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://freepik_user:freepik_pass@postgres:5432/freepik_orchestrator
      - ENVIRONMENT=production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: freepik_orchestrator
      POSTGRES_USER: freepik_user
      POSTGRES_PASSWORD: freepik_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  webhook:
    build: .
    command: ["python", "-m", "uvicorn", "webhook_server:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - FREEPIK_WEBHOOK_SECRET=${FREEPIK_WEBHOOK_SECRET}
      - DATABASE_URL=postgresql://freepik_user:freepik_pass@postgres:5432/freepik_orchestrator
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
